package export

import (
	"fmt"
	"strings"
)

// readmeMD renders readme.md, the project's front door: what the system is,
// every token family the sheet emits (enumerated from the same tables the
// CSS emitter renders from, so the two cannot drift), ADR-007's step
// purposes, pointers to the foundation pages, and the reproducibility
// contract theme.json carries.
func readmeMD(s Snapshot) string {
	var b strings.Builder

	b.WriteString("# Vibrant Gio — design tokens\n\n")
	fmt.Fprintf(&b, "Vibrant Gio is a generative design system for [Gio](https://gioui.org) desktop\n"+
		"applications. The entire colour system derives from one brand seed — currently\n"+
		"`%s` — through `theme/tokens.FromSeed`: every colour role carries a\n"+
		"**nine-step functional ramp (100–900)** on a shared lightness scale, with the\n"+
		"role's **base pinned separately** so the brand colour is reproduced exactly, and\n"+
		"**dark mode is the paired ramp** — the same step keeps the same job in both\n"+
		"modes, so nothing is assigned twice. The contrast gate is APCA\n"+
		"(step 900 reaches |Lc| 90 and step 700 |Lc| 60 over the 100/200 grounds, every\n"+
		"pin's on-colour |Lc| 60 over its pin); WCAG 2 ratios are reported alongside but\n"+
		"do not gate.\n\n", hexRGB(s.Seed))

	b.WriteString("This directory is generated by `theme/export` (`cmd/vg-tokens`); do not edit\n" +
		"it by hand — regenerate it.\n\n")

	b.WriteString("## Files\n\n" +
		"- `styles.css` — the token sheet: one `:root` block (light colours plus every\n" +
		"  mode-invariant scale, comfortable density), one `.dark` class override block\n" +
		"  (the paired dark colours only) and one `.compact` class override block (the\n" +
		"  compact density metrics only). Add `class=\"dark\"` to the root element to\n" +
		"  switch modes, `class=\"compact\"` to any subtree to densify it; the two\n" +
		"  switches are orthogonal. Below the token blocks sits the component class\n" +
		"  layer (`.btn` and its modifiers) — see Component classes.\n" +
		"- `theme.json` — the generative parameters; see the reproducibility contract\n" +
		"  below.\n" +
		"- `foundations/color.html` — every ramp, pin, step purpose and measured\n" +
		"  APCA Lc / WCAG ratio per text pair, in both modes.\n" +
		"- `foundations/type.html` — every type role at its real metrics.\n" +
		"- `fonts/` — the faces behind `--font-family` and `--font-family-code`,\n" +
		"  self-hosted with their licences: the same Roboto regular and medium the\n" +
		"  Gio applications embed, and Roboto Mono from the font repository.\n" +
		"- `foundations/layout.html` — the spacing scale, the control metrics at both\n" +
		"  density settings, the radius scale and tonal elevation as rendered\n" +
		"  specimens.\n" +
		"- `components/*.html` — hand-authored component pages (not generated):\n" +
		"  every class-layer component in every register and state, at both\n" +
		"  densities, as copyable markup. `buttons.html` covers `.btn` and `.tag`,\n" +
		"  `forms.html` the native-element form controls.\n\n" +
		"Each page reads only from `styles.css` — every styled value is a `var(--…)`\n" +
		"reference — and carries a light/dark toggle. Annotation numbers are printed for\n" +
		"both modes, labelled `L` and `D`.\n\n")

	b.WriteString("## Token families\n\n")
	b.WriteString("| Family | Tokens | Notes |\n| --- | --- | --- |\n")
	for _, role := range rampRoles {
		fmt.Fprintf(&b, "| `--color-%[1]s-<step>` | `--color-%[1]s-100` … `--color-%[1]s-900` | the %[1]s ramp; steps in hundreds |\n", role.name)
	}
	pinNames := make([]string, len(pinRoles))
	for i, pin := range pinRoles {
		pinNames[i] = "`--color-" + pin.name + "`"
	}
	fmt.Fprintf(&b, "| pins & semantic layer | %s | pinned bases, their on-colours, the ramp-resolved surface/divider, the inverse pair the counterpart scheme's ramp resolves, and the control marks each ramp measures for itself — the checkbox's edge and the two focus-ring grounds |\n", strings.Join(pinNames, ", "))
	b.WriteString("| `--font-family` | `--font-family` | the typeface every prose role uses |\n")
	b.WriteString("| `--font-family-code` | `--font-family-code` | the monospace typeface the code role uses |\n")
	typeNames := make([]string, len(typeRoles))
	for i, role := range typeRoles {
		typeNames[i] = role.name
	}
	fmt.Fprintf(&b, "| `--font-<role>-*` | roles %s; each with `-size`, `-line-height`, `-weight`, `-tracking` | px sizes, CSS numeric weights; code is the mono style outside the MD3 grid, at body-medium's metrics |\n", strings.Join(typeNames, ", "))
	fmt.Fprintf(&b, "| `--density-<metric>` | %s, `--density-min-hit-target` | control metrics, px; `:root` is comfortable, `.compact` overrides all but the hit-target floor |\n", joinTokens("--density-", densityNames()))
	fmt.Fprintf(&b, "| `--space-<key>` | %s | the 4-pt spacing grid, px |\n", joinTokens("--space-", spaceNames()))
	fmt.Fprintf(&b, "| `--radius-<key>` | %s | corner radii, Tailwind naming, px |\n", joinTokens("--radius-", radiusNames()))
	fmt.Fprintf(&b, "| `--elevation-<level>` | %s | tonal surface fills — the DEFAULT elevation cue; `var()` references into the neutral ramp (level 0 is the bg pin), so they flip with `.dark` |\n", joinTokens("--elevation-", elevationNames()))
	fmt.Fprintf(&b, "| `--shadow-<level>` | %s | dp box-shadows — the OPT-IN cue for floating transients (menus, dialogs, tooltips) layered over the tonal fill; resting surfaces use the fill alone |\n", joinTokens("--shadow-", elevationNames()))
	fmt.Fprintf(&b, "| `--ease-<name>` | %s | MD3 easing presets as `cubic-bezier()`; emphasized is the documented single-bezier stand-in for MD3's two-segment path |\n", joinTokens("--ease-", easeNames()))
	fmt.Fprintf(&b, "| `--duration-<stop>` | %s | MD3-pinned duration stops, ms; the reduce-motion variant zeroes them |\n", joinTokens("--duration-", durationNames()))
	b.WriteString("| interaction states | `--focus-ring-width`, `--state-disabled-opacity` | the ring's 2 px stroke and the disabled fade fraction for `color-mix()` — both mode-invariant, unlike the ring's colour, which is measured against a ground that flips and so sits with the colours above |\n")
	b.WriteString("| scrim | `--color-scrim` | the modal backdrop dimmer: translucent black, identical in both modes — a scrim dims by reducing luminance, so it never flips with `.dark`. The alpha is the sRGB-compositing equivalent of the Gio pattern's 50% linear-space black |\n\n")

	b.WriteString("## Step purposes\n\n" +
		"| Step | Job |\n| --- | --- |\n" +
		"| 100 | tinted fill · app ground |\n" +
		"| 200 | tinted fill · card / raised surface |\n" +
		"| 300 | hover · subtle border, separator |\n" +
		"| 400 / 600 / 800 | intermediate steps; interaction states walk through them |\n" +
		"| 500 | mid-value reference · strong border |\n" +
		"| 700 | low-contrast text (Lc ≥ 60) · pressed |\n" +
		"| 900 | high-contrast body text (Lc ≥ 90) · pressed |\n\n" +
		"The pinned base — not a ramp step — is the solid fill; hover and pressed on a\n" +
		"solid walk one and two steps from the pin toward 900.\n\n")

	b.WriteString("## Component classes\n\n" +
		"`styles.css` ends with the component class layer, defined over the tokens\n" +
		"above — no literal colours anywhere, the only literal lengths being the\n" +
		"component constants the Gio side also hardcodes (the 20 dp checkbox/radio\n" +
		"glyph, its 10 dp dot, the 16 dp dropdown chevron, the 1/2 dp input\n" +
		"borders) — so it re-brands, flips to `.dark` and densifies to `.compact`\n" +
		"with the sheet. Every pointer/keyboard state rule carries a forcing twin\n" +
		"class (`.is-hover`, `.is-active`, `.is-focus`, `.is-checked`) grouped into\n" +
		"the same rule, so a static page can show a state with exactly the live\n" +
		"declarations; disabled is forced with the native attribute.\n\n" +
		"`.btn` is the button, **filled** by default: the accent pin under its\n" +
		"on-colour. Two modifier classes select the quieter emphasis registers —\n" +
		"`.btn.tonal` (a tinted fill: primary 200 under primary 900 text) and\n" +
		"`.btn.ghost` (no ground at rest; neutral 700 text). Interaction states\n" +
		"resolve as the step walks above: hover walks one step (`:hover`), pressed\n" +
		"and selected two (`:active`, `.selected`); a filled button's solid fill\n" +
		"walks via the emitted `--color-accent-hover` / `--color-accent-pressed`\n" +
		"stops. Keyboard focus (`:focus-visible`) keeps the resting fill and draws\n" +
		"the ring: `--focus-ring-width` of the rung its ramp measures against the\n" +
		"ground the ring circles — `--color-focus-ring-on-accent` over a filled\n" +
		"button's own fill, `--color-focus-ring` everywhere else. Same ring, same\n" +
		"width, same 3:1 floor in every register; only the ground moves.\n" +
		"Disabled (`:disabled`) fades each colour to\n" +
		"`--state-disabled-opacity` of its alpha. A ghost has no selected\n" +
		"treatment: it stays quiet. `.btn.icon` is the icon-only form: a square\n" +
		"the density's control height on a side, the glyph (an inline SVG on\n" +
		"`currentColor`) inset by the density's vertical padding.\n\n" +
		"`.tag` is the chip the patterns draw: a Full-radius pill at `label-small`\n" +
		"metrics with S1/S2 padding — filled (accent under on-accent) by default,\n" +
		"`.tag.tonal` the primary-200 tinted fill under the accent pin. Status\n" +
		"chips are `.tag.success` / `.tag.warning` / `.tag.error`: the level\n" +
		"pin tinted 20% over the Surface ground, ringed by the 1 dp level\n" +
		"outline, under the text pin. Compose them for status; never inline-style a\n" +
		"status colour. Tags are labels, not controls: no interaction states.\n\n" +
		"The form controls dress native elements — no script anywhere:\n" +
		"`.input` (text `<input>`, and `<select class=\"input select\">` inside a\n" +
		"`.select-wrap` for the chevron), `.checkbox` and `.radio` on their native\n" +
		"input types with `appearance: none`. They resolve exactly as\n" +
		"`components/input` does: Surface ground under `body-large` text, neutral\n" +
		"500 strong border on the text field and the radio, neutral 700 placeholder\n" +
		"and chevron, focus promoting the border to the accent pin (2 dp on the\n" +
		"text field, the shared ring on checkbox/radio), disabled fading every\n" +
		"colour via `color-mix()`. The checkbox edges itself with\n" +
		"`--color-checkbox-border` instead — the neutral rung its own ramp measures\n" +
		"as reaching 3:1 against the window ground, which is 600 in the light\n" +
		"scheme and 500 in the dark; one named rung would read below the floor in\n" +
		"one of them. Checked, the box is the accent fill under a check mark in the\n" +
		"on-accent pin, drawn from the icon set's grid as two gradient bands — a\n" +
		"fill says a colour was applied and only the mark says what it means. The\n" +
		"radio's selected state is the accent ring and 10 dp dot around a Surface\n" +
		"gap.\n\n")

	b.WriteString("## Elevation: default vs opt-in\n\n" +
		"Elevation is tonal: a raised surface separates from its ground by\n" +
		"colour, one neutral-ramp step per storey — level 0 is the bg pin over the\n" +
		"step-100 ground and levels 1–3 fill with neutral 200/300/400. The ladder\n" +
		"stops at 3: desktop has no six-storey stack. `--elevation-N`\n" +
		"is that surface fill and the **default** cue; because the light and dark\n" +
		"ramps are paired scales, the same level reads as raised in both modes with\n" +
		"no mode-specific rule. The dp shadow is the **opt-in** secondary cue,\n" +
		"reserved for floating transients — menus, dialogs, tooltips — which layer\n" +
		"`--shadow-N` over their tonal fill. Resting surfaces never cast one.\n\n")

	b.WriteString("## Density\n\n" +
		"Two published settings, one variable family: comfortable (36 dp controls,\n" +
		"16/8 dp padding) is the `:root` default; compact (28 dp, 12/6 dp) is the\n" +
		"`.compact` class override, scoping to any subtree the way `.dark` scopes\n" +
		"colours. `--density-min-hit-target` (44 dp, WCAG 2.5.5) is deliberately not\n" +
		"overridden: compact shrinks the drawn control, never the clickable area.\n" +
		"`theme.json` records both settings' metrics plus which one the theme runs.\n\n")

	b.WriteString("## Motion\n\n" +
		"The MD3 easing presets are emitted as `cubic-bezier()` variables and the\n" +
		"five duration stops in ms, each pinned to one MD3 duration role. The spring\n" +
		"presets (default/snappy/gentle) are Go-side damped-oscillator physics with\n" +
		"no CSS counterpart, so they live only in `theme.json`'s motion parameters.\n" +
		"Under the OS reduce-motion preference the theme emits the same scale with\n" +
		"every duration zeroed; the sheet is generated from the non-reduced scale.\n\n")

	b.WriteString("## Reproducibility\n\n" +
		"`theme.json` records the seed (hex plus its OKLCh hue and sat), the pinned role\n" +
		"hexes per mode, the faces, the base radius, the measured lightness scales, both\n" +
		"density settings' metrics, the elevation model (surface steps and shadow dps\n" +
		"per level) and the motion set (durations, easings, springs).\n" +
		"`FromSeed(seed)` regenerates every ramp and pin from the seed alone — a\n" +
		"round-trip test in `theme/export` asserts it — so the file, not this text,\n" +
		"is the contract. To rebrand, rerun `vg-tokens -seed #rrggbb`; every page here\n" +
		"reflows because nothing in them is hard-coded.\n\n" +
		"Fonts: the tokens name " + s.Typography.BodyLarge.Typeface + " (and " + s.Typography.Code.Typeface + " for code); the pages fall\n" +
		"back to system faces when they are not installed. An increased-contrast palette variant exists Go-side\n" +
		"(`tokens.FromSeedHighContrast`, driven by the OS contrast preference); it is\n" +
		"not part of this export.\n")

	return b.String()
}

// spaceNames, radiusNames and elevationNames list each scale's key names in
// sheet order, for the readme's enumerations.
func spaceNames() []string {
	names := make([]string, len(spaceKeys))
	for i, k := range spaceKeys {
		names[i] = k.name
	}
	return names
}

func radiusNames() []string {
	names := make([]string, len(radiusKeys))
	for i, k := range radiusKeys {
		names[i] = k.name
	}
	return names
}

func elevationNames() []string {
	names := make([]string, len(elevationLevels))
	for i, k := range elevationLevels {
		names[i] = k.name
	}
	return names
}

// densityNames, easeNames and durationNames list the density metric, easing
// preset and duration stop names in sheet order, for the readme's
// enumerations.
func densityNames() []string {
	names := make([]string, len(densityMetrics))
	for i, m := range densityMetrics {
		names[i] = m.name
	}
	return names
}

func easeNames() []string {
	names := make([]string, len(easeRoles))
	for i, r := range easeRoles {
		names[i] = r.name
	}
	return names
}

func durationNames() []string {
	names := make([]string, len(durationStops))
	for i, s := range durationStops {
		names[i] = s.name
	}
	return names
}

// joinTokens renders a comma-separated code list of prefix+name tokens.
func joinTokens(prefix string, names []string) string {
	out := make([]string, len(names))
	for i, n := range names {
		out[i] = "`" + prefix + n + "`"
	}
	return strings.Join(out, ", ")
}
