package export

import (
	"fmt"
	"strings"
)

// readmeMD renders readme.md, the project's front door: what the system is,
// every token family the sheet emits (enumerated from the same tables the
// CSS emitter renders from, so the two cannot drift), the step purposes,
// pointers to the foundation pages, and the reproducibility
// contract theme.json carries.
func readmeMD(s Snapshot) string {
	var b strings.Builder

	b.WriteString("# Vibrant Gio — design tokens\n\n")
	fmt.Fprintf(&b, "Vibrant Gio is a design system for [Gio](https://gioui.org) desktop\n"+
		"applications. Its colour vocabulary is the platform's own: one variable per\n"+
		"AppKit semantic colour name, carrying the value that name reports under each\n"+
		"appearance, plus the fills the platform draws without naming one, measured off\n"+
		"stored captures. Nothing is derived from anything. The one colour a user\n"+
		"chooses is the theme colour — currently `%s` — which stands in wherever the\n"+
		"platform paints its accent: the default button, the selection, the focus ring,\n"+
		"the sidebar's pill. The contrast measure is APCA, reported per pair on the\n"+
		"colour page.\n\n", hexRGB(s.PlatformLight.ControlAccent))

	b.WriteString("This directory is generated by `theme/export` (`cmd/vg-tokens`); do not edit\n" +
		"it by hand — regenerate it.\n\n")

	b.WriteString("## Files\n\n" +
		"- `styles.css` — the token sheet: one `:root` block (the platform's light\n" +
		"  set plus every mode-invariant scale, comfortable density),\n" +
		"  one `.dark` class override block (the platform's dark set)\n" +
		"  and one `.compact` class override block (the\n" +
		"  compact density metrics only). Add `class=\"dark\"` to the root element to\n" +
		"  switch modes, `class=\"compact\"` to any subtree to densify it; the two\n" +
		"  switches are orthogonal. Below the token blocks sits the component class\n" +
		"  layer (`.btn` and its modifiers) — see Component classes.\n" +
		"- `theme.json` — the generative parameters; see the reproducibility contract\n" +
		"  below.\n" +
		"- `foundations/color.html` — every name in the platform's set, both\n" +
		"  appearances, with the measured APCA Lc of the pairs the platform makes.\n" +
		"- `foundations/type.html` — every type role at its real metrics.\n" +
		"- `fonts/` — the faces behind `--font-family` and `--font-family-code`,\n" +
		"  self-hosted with their licences: the same Roboto regular and medium the\n" +
		"  Gio applications embed, and Roboto Mono from the font repository.\n" +
		"- `foundations/layout.html` — the spacing scale, the control metrics at both\n" +
		"  density settings, the radius scale and the shadow depth each level casts,\n" +
		"  as rendered specimens.\n" +
		"- `components/*.html` — hand-authored component pages (not generated):\n" +
		"  every class-layer component in every variant and state, at both\n" +
		"  densities, as copyable markup. `buttons.html` covers `.btn` and `.badge`,\n" +
		"  `forms.html` the native-element form controls.\n\n" +
		"Each page reads only from `styles.css` — every styled value is a `var(--…)`\n" +
		"reference — and carries a light/dark toggle. Annotation numbers are printed for\n" +
		"both modes, labelled `L` and `D`.\n\n")

	b.WriteString("## Token families\n\n")
	b.WriteString("| Family | Tokens | Notes |\n| --- | --- | --- |\n")
	platformVarNames := make([]string, len(platformNames))
	for i, n := range platformNames {
		platformVarNames[i] = "`--platform-" + n.name + "`"
	}
	fmt.Fprintf(&b, "| `--platform-<name>` | %s | the platform's own colour set: AppKit's semantic colours under their own names, kebab-cased, plus the fills the platform draws without naming, measured. Both schemes state their own. A coverage is written out as `#rrggbbaa`, because the platform's answer for a label, a seam, an overlay or the focus ring IS a colour at a coverage over whatever lies beneath it |\n", strings.Join(platformVarNames, ", "))
	b.WriteString("| `--font-family` | `--font-family` | the typeface every prose role uses |\n")
	b.WriteString("| `--font-family-code` | `--font-family-code` | the monospace typeface the code role uses |\n")
	typeNames := make([]string, len(typeRoles))
	for i, role := range typeRoles {
		typeNames[i] = role.name
	}
	fmt.Fprintf(&b, "| `--font-<role>-*` | roles %s; each with `-size`, `-line-height`, `-weight`, `-tracking` | px sizes, CSS numeric weights; code is the mono style outside the type grid, at body-medium's metrics |\n", strings.Join(typeNames, ", "))
	fmt.Fprintf(&b, "| `--density-<metric>` | %s, `--density-min-hit-target` | control metrics, px; `:root` is comfortable, `.compact` overrides all but the hit-target floor |\n", joinTokens("--density-", densityNames()))
	fmt.Fprintf(&b, "| `--space-<key>` | %s | the 4-pt spacing grid, px |\n", joinTokens("--space-", spaceNames()))
	fmt.Fprintf(&b, "| `--radius-<key>` | %s | corner radii, Tailwind naming, px |\n", joinTokens("--radius-", radiusNames()))
	fmt.Fprintf(&b, "| `--shadow-<level>` | %s | dp box-shadows — the cue a floating transient carries (menus, dialogs, tooltips) over the platform fill it stands in; resting surfaces cast none |\n", joinTokens("--shadow-", shadowNames()))
	fmt.Fprintf(&b, "| `--ease-<name>` | %s | easing presets as `cubic-bezier()`; emphasized is the documented single-bezier stand-in for the published two-segment path |\n", joinTokens("--ease-", easeNames()))
	fmt.Fprintf(&b, "| `--duration-<stop>` | %s | duration stops, ms; the reduce-motion variant zeroes them |\n", joinTokens("--duration-", durationNames()))
	b.WriteString("| interaction states | `--focus-ring-width` | the ring's 2 px stroke, mode-invariant, unlike the ring's colour, which is `--platform-keyboard-focus-indicator` and flips with the appearance |\n\n")

	b.WriteString("## Component classes\n\n" +
		"`styles.css` ends with the component class layer, defined over the tokens\n" +
		"above — no literal colours anywhere, the only literal lengths being the\n" +
		"component constants the Gio side also hardcodes (the 16 dp\n" +
		"checkbox/radio glyph, its 8 dp dot, the 16 dp dropdown chevron, the\n" +
		"1/2 dp input borders) — so it flips to `.dark` and densifies to\n" +
		"`.compact` with the sheet. Every colour in it is the platform's own\n" +
		"name for what that element is on the platform, the same mapping the Gio\n" +
		"components take: nothing is derived, every value is a platform name. Every\n" +
		"pointer/keyboard state rule carries a forcing twin class (`.is-hover`,\n" +
		"`.is-active`, `.is-focus`, `.is-checked`) grouped into the same rule, so\n" +
		"a static page can show a state with exactly the live declarations;\n" +
		"disabled is forced with the native attribute.\n\n" +
		"A coverage composites the same on both sides, and that is what lets a\n" +
		"rule name a platform colour and stop: the platform's labels, seams,\n" +
		"overlays and focus ring are a colour at a coverage over whatever lies\n" +
		"beneath, a browser composites `#rrggbbaa` in encoded sRGB, and so does\n" +
		"`theme/color.Flatten` on the Gio side. Where the Gio component flattens\n" +
		"a name onto its own fill, the CSS lets the element's background paint\n" +
		"under the border, as it does by default; where it flattens onto the\n" +
		"surface the control stands on instead — a text field's focus ring, a\n" +
		"checkbox's edge — the rule sets `background-clip: padding-box` so the\n" +
		"edge composites over the page. That pair of clips is the whole of what\n" +
		"a control needs to know about its host; nothing is handed down.\n\n" +
		"`.btn` is the button, **filled** by default: `--platform-control-accent`\n" +
		"under `--platform-alternate-selected-control-text`, which is the\n" +
		"platform's default action. Two modifier classes select the less\n" +
		"pronounced variants — `.btn.tonal`, the platform's ordinary push button\n" +
		"(`--platform-push-button-fill` under `--platform-control-text`, inside a\n" +
		"`--platform-separator` hairline), and `.btn.ghost`, its borderless kind\n" +
		"(no fill, `--platform-control-text`). Nothing tints on hover: a Finder\n" +
		"toolbar button does and a Save dialog's push button does not, and this\n" +
		"sheet's classes are push buttons. Held (`:active`),\n" +
		"`--platform-press-overlay` goes over whatever fill the variant carries\n" +
		"and over the page where it carries none. Keyboard focus\n" +
		"(`:focus-visible`) keeps the resting fill and insets\n" +
		"`--platform-keyboard-focus-indicator` at `--focus-ring-width` — the same\n" +
		"ring at the same width in every variant, because keyboard visibility is\n" +
		"not a prominence property. Disabled (`:disabled`) is the platform's own\n" +
		"answer rather than a fade: the fill falls back to the push button's\n" +
		"inside the separator hairline and every foreground becomes\n" +
		"`--platform-disabled-control-text`. `.btn.icon` is the icon-only form: a\n" +
		"square the density's control height on a side, the glyph (an inline SVG\n" +
		"on `currentColor`) inset by the density's vertical padding.\n\n" +
		"`.badge` is the inline annotation: `label-medium` text on the platform's\n" +
		"system colour for the status it carries, under\n" +
		"`--platform-alternate-selected-control-text` — white in both\n" +
		"appearances, which is how the platform draws a count badge. The default\n" +
		"is `--platform-system-gray`, the platform naming no colour for \"no\n" +
		"status\"; `.badge.success` / `.badge.warning` / `.badge.error` /\n" +
		"`.badge.info` are systemGreen, systemOrange, systemRed and systemBlue.\n" +
		"Never invert the pair and never tint the system colour toward the\n" +
		"surface. No boundary and no vertical padding, so its height is the\n" +
		"role's line box; the side padding is `--space-2` and the corner is\n" +
		"`--radius-base`, deliberately not the pill a chip wears. A badge is\n" +
		"read, not used: no interaction states.\n\n" +
		"The form controls dress native elements — no script anywhere:\n" +
		"`.input` (text `<input>`, and `<select class=\"input select\">` inside a\n" +
		"`.select-wrap` for the chevron), `.checkbox` and `.radio` on their\n" +
		"native input types with `appearance: none`. They resolve exactly as\n" +
		"`components/input` does: `--platform-text-background` under\n" +
		"`--platform-text`, `--platform-placeholder-text` for a prompt,\n" +
		"`--platform-field-edge` on the resting edge, focus replacing that edge\n" +
		"with `--platform-keyboard-focus-indicator` at `--focus-ring-width`, and\n" +
		"`--platform-disabled-control-text` where the control cannot be used —\n" +
		"the fill staying exactly where it was, because the platform fades the\n" +
		"wording and leaves the control. A text field's height floor is\n" +
		"`--density-field-height`, not the control height: the platform draws a\n" +
		"field shorter than the button beside it. The dropdown trigger is the\n" +
		"exception in this family and is a BUTTON rather than a field, so\n" +
		"`.select` takes the push button's fill, the separator hairline and the\n" +
		"control height. Checked, the box is `--platform-control-accent` under a\n" +
		"check mark drawn from the icon set's grid as two gradient bands — a fill\n" +
		"says a colour was applied and only the mark says what it means. The\n" +
		"radio's selected state is the same accent filling the circle with an\n" +
		"8 dp white dot at its centre.\n\n" +
		"`.card` is the platform's grouped box: `--platform-card-fill`, a small\n" +
		"step of fill from the surface it stands on, with no hairline and no\n" +
		"shadow. `.group` is the other half of that ruling — a\n" +
		"`--platform-separator` hairline around related components, taking the\n" +
		"fill of the surface it is in and declaring none. `.table` prints on\n" +
		"`--platform-control-background` with rows a `--density-row-height`\n" +
		"tall, `--platform-grid` closing each and `--platform-separator` closing\n" +
		"the header band. The navigation family — `.navbar`, `.tabs`, `.sidebar`\n" +
		"and `.crumbs` — stands on `--platform-sidebar-material`, the chrome, and\n" +
		"draws the separator where two flush regions meet; selection is\n" +
		"`--platform-selected-content-background`, as an underline on a link or a\n" +
		"tab and as the row's own fill on a rail. The overlay family —\n" +
		"`.scrim`/`.dialog`, `.popover`, `.tooltip`, `.toast` — is filled with\n" +
		"`--platform-window-background`, which is what every floating surface on\n" +
		"this platform is filled with, and floats on\n" +
		"`--platform-floating-shadow`.\n\n")

	b.WriteString("## Levels and the shadow\n\n" +
		"A level's FILL is the platform's own name for what that region is, not a\n" +
		"derivation: the window's plane under `--platform-window-background`, the\n" +
		"chrome under `--platform-sidebar-material`, the content under\n" +
		"`--platform-control-background`, a card under `--platform-card-fill`, and\n" +
		"every floating surface under `--platform-window-background` again, which\n" +
		"is what this platform fills a dialog, a menu and a popover with. Six\n" +
		"levels, counted from the backdrop up toward the reader: the bare window\n" +
		"plane, the chrome a window wears, the content surface, a raised inset, and\n" +
		"the two floating levels. The levels stop at 3: desktop has no six-deep\n" +
		"stack. Chrome is window-scale only — the trim inside a component or a\n" +
		"pattern is that thing's structure and takes no level of its own.\n\n" +
		"What the sheet states per level is the shadow: `--shadow-<level>`, the cue\n" +
		"a floating transient carries over its fill. Neither level under the content\n" +
		"casts anything, and a resting surface never does.\n\n")

	b.WriteString("## Density\n\n" +
		"Two published settings, one variable family: comfortable (24 dp controls,\n" +
		"20 dp chips, 8/2 dp padding) is the `:root` default; compact (19 dp\n" +
		"controls, 15 dp chips, 7/0 dp padding) is the `.compact` class override,\n" +
		"scoping to any subtree the way `.dark` scopes colours. The chip height is\n" +
		"the control height less 4 dp in both settings — one relation, not a second\n" +
		"scale. A text field and a stacked row are not controls and carry their own\n" +
		"measured heights: `--density-field-height` (27 dp comfortable, 21 compact)\n" +
		"and `--density-row-height` (20 dp, 19 compact).\n" +
		"`--density-min-hit-target` (44 dp, WCAG 2.5.5) is deliberately not\n" +
		"overridden: compact shrinks the drawn control, never the clickable area.\n" +
		"`theme.json` records both settings' metrics plus which one the theme runs.\n\n")

	b.WriteString("## Motion\n\n" +
		"The easing presets are emitted as `cubic-bezier()` variables and the\n" +
		"five duration stops in ms, each pinned to one duration role. The spring\n" +
		"presets (default/snappy/gentle) are Go-side damped-oscillator physics with\n" +
		"no CSS counterpart, so they live only in `theme.json`'s motion parameters.\n" +
		"Under the OS reduce-motion preference the theme emits the same scale with\n" +
		"every duration zeroed; the sheet is generated from the non-reduced scale.\n\n")

	b.WriteString("## Reproducibility\n\n" +
		"`theme.json` records the theme colour, the platform's whole set per\n" +
		"appearance keyed by the same names the sheet carries, the faces, the base\n" +
		"radius, both density settings' metrics, the shadow depth per level and the\n" +
		"motion set (durations, easings, springs). A round-trip test in\n" +
		"`theme/export` asserts the file and the sheet agree value for value, so the\n" +
		"file, not this text, is the contract. To change the theme colour, rerun\n" +
		"`vg-tokens -color #rrggbb`; every page here reflows because nothing in them\n" +
		"is hard-coded.\n\n" +
		"Fonts: the tokens name " + s.Typography.BodyLarge.Typeface + " (and " + s.Typography.Code.Typeface + " for code); the pages fall\n" +
		"back to system faces when they are not installed. The OS increased-contrast\n" +
		"preference needs no variant of its own: on macOS the platform reports the\n" +
		"values it paints under it, and the set follows.\n")

	return b.String()
}

// spaceNames, radiusNames and shadowNames list each scale's key names in
// sheet order, for the readme's enumerations.
func spaceNames() []string {
	names := make([]string, len(spaceKeys))
	for i, k := range spaceKeys {
		names[i] = k.name
	}
	return names
}

func radiusNames() []string {
	names := make([]string, len(radiusKeys))
	for i, k := range radiusKeys {
		names[i] = k.name
	}
	return names
}

func shadowNames() []string {
	names := make([]string, len(shadowLevels))
	for i, k := range shadowLevels {
		names[i] = k.name
	}
	return names
}

func densityNames() []string {
	names := make([]string, len(densityMetrics))
	for i, m := range densityMetrics {
		names[i] = m.name
	}
	return names
}

func easeNames() []string {
	names := make([]string, len(easeRoles))
	for i, r := range easeRoles {
		names[i] = r.name
	}
	return names
}

func durationNames() []string {
	names := make([]string, len(durationStops))
	for i, s := range durationStops {
		names[i] = s.name
	}
	return names
}

// joinTokens renders a comma-separated code list of prefix+name tokens.
func joinTokens(prefix string, names []string) string {
	out := make([]string, len(names))
	for i, n := range names {
		out[i] = "`" + prefix + n + "`"
	}
	return strings.Join(out, ", ")
}
