package export

import (
	"fmt"
	"strings"
)

// readmeMD renders readme.md, the project's front door: what the system is,
// every token family the sheet emits (enumerated from the same tables the
// CSS emitter renders from, so the two cannot drift), the step purposes,
// pointers to the foundation pages, and the reproducibility
// contract theme.json carries.
func readmeMD(s Snapshot) string {
	var b strings.Builder

	b.WriteString("# Vibrant Gio — design tokens\n\n")
	fmt.Fprintf(&b, "Vibrant Gio is a generative design system for [Gio](https://gioui.org) desktop\n"+
		"applications. The entire colour system derives from one brand seed — currently\n"+
		"`%s` — through `theme/tokens.FromSeed`: every colour role carries a\n"+
		"**nine-step functional ramp (100–900)** on a shared lightness scale, with the\n"+
		"role's **base pinned separately** so the brand colour is reproduced exactly, and\n"+
		"**dark mode is the paired ramp** — the same step keeps the same job in both\n"+
		"modes, so nothing is assigned twice. The contrast gate is APCA\n"+
		"(step 900 reaches |Lc| 90 and step 700 |Lc| 60 over the 100/200 surfaces, every\n"+
		"pin's on-colour |Lc| 60 over its pin); it is the one contrast measure the\n"+
		"palette is derived and reported in.\n\n", hexRGB(s.Seed))

	b.WriteString("This directory is generated by `theme/export` (`cmd/vg-tokens`); do not edit\n" +
		"it by hand — regenerate it.\n\n")

	b.WriteString("## Files\n\n" +
		"- `styles.css` — the token sheet: one `:root` block (light colours and\n" +
		"  elevation levels plus every mode-invariant scale, comfortable density),\n" +
		"  one `.dark` class override block (the paired dark colours and levels)\n" +
		"  and one `.compact` class override block (the\n" +
		"  compact density metrics only). Add `class=\"dark\"` to the root element to\n" +
		"  switch modes, `class=\"compact\"` to any subtree to densify it; the two\n" +
		"  switches are orthogonal. Below the token blocks sits the component class\n" +
		"  layer (`.btn` and its modifiers) — see Component classes.\n" +
		"- `theme.json` — the generative parameters; see the reproducibility contract\n" +
		"  below.\n" +
		"- `foundations/color.html` — every ramp, pin, step purpose and measured\n" +
		"  APCA Lc per text pair, in both modes.\n" +
		"- `foundations/type.html` — every type role at its real metrics.\n" +
		"- `fonts/` — the faces behind `--font-family` and `--font-family-code`,\n" +
		"  self-hosted with their licences: the same Roboto regular and medium the\n" +
		"  Gio applications embed, and Roboto Mono from the font repository.\n" +
		"- `foundations/layout.html` — the spacing scale, the control metrics at both\n" +
		"  density settings, the radius scale and tonal elevation as rendered\n" +
		"  specimens.\n" +
		"- `components/*.html` — hand-authored component pages (not generated):\n" +
		"  every class-layer component in every variant and state, at both\n" +
		"  densities, as copyable markup. `buttons.html` covers `.btn` and `.badge`,\n" +
		"  `forms.html` the native-element form controls.\n\n" +
		"Each page reads only from `styles.css` — every styled value is a `var(--…)`\n" +
		"reference — and carries a light/dark toggle. Annotation numbers are printed for\n" +
		"both modes, labelled `L` and `D`.\n\n")

	b.WriteString("## Token families\n\n")
	b.WriteString("| Family | Tokens | Notes |\n| --- | --- | --- |\n")
	for _, role := range rampRoles {
		fmt.Fprintf(&b, "| `--color-%[1]s-<step>` | `--color-%[1]s-100` … `--color-%[1]s-900` | the %[1]s ramp; steps in hundreds |\n", role.name)
	}
	pinNames := make([]string, len(pinRoles))
	for i, pin := range pinRoles {
		pinNames[i] = "`--color-" + pin.name + "`"
	}
	fmt.Fprintf(&b, "| pins & semantic layer | %s | pinned bases, their on-colours, the ramp-resolved surface/seam, the inverse pair the counterpart scheme's ramp resolves, the reserved highlighter no status hue may serve, and the edges and rings each ramp measures for itself — a resting border for the page, the dialog and the popover, and one focus ring for the whole scheme, measured against every level at once, plus the accent fill a filled button's ring lies on, which belongs to no level at all |\n", strings.Join(pinNames, ", "))
	platformVarNames := make([]string, len(platformNames))
	for i, n := range platformNames {
		platformVarNames[i] = "`--platform-" + n.name + "`"
	}
	fmt.Fprintf(&b, "| `--platform-<name>` | %s | the platform's own colour set: AppKit's semantic colours under their own names, kebab-cased, plus the ten fills the platform draws without naming, measured. Both schemes state their own. A coverage is written out as `#rrggbbaa`, because the platform's answer for a label, a seam, an overlay or the focus ring IS a colour at a coverage over whatever lies beneath it |\n", strings.Join(platformVarNames, ", "))
	b.WriteString("| `--font-family` | `--font-family` | the typeface every prose role uses |\n")
	b.WriteString("| `--font-family-code` | `--font-family-code` | the monospace typeface the code role uses |\n")
	typeNames := make([]string, len(typeRoles))
	for i, role := range typeRoles {
		typeNames[i] = role.name
	}
	fmt.Fprintf(&b, "| `--font-<role>-*` | roles %s; each with `-size`, `-line-height`, `-weight`, `-tracking` | px sizes, CSS numeric weights; code is the mono style outside the MD3 grid, at body-medium's metrics |\n", strings.Join(typeNames, ", "))
	fmt.Fprintf(&b, "| `--density-<metric>` | %s, `--density-min-hit-target` | control metrics, px; `:root` is comfortable, `.compact` overrides all but the hit-target floor |\n", joinTokens("--density-", densityNames()))
	fmt.Fprintf(&b, "| `--space-<key>` | %s | the 4-pt spacing grid, px |\n", joinTokens("--space-", spaceNames()))
	fmt.Fprintf(&b, "| `--radius-<key>` | %s | corner radii, Tailwind naming, px |\n", joinTokens("--radius-", radiusNames()))
	fmt.Fprintf(&b, "| `--elevation-<level>` | %s | tonal surface fills — the DEFAULT elevation cue; ordered from the backdrop up toward the reader, and resolved per scheme, so both blocks state their own six |\n", joinTokens("--elevation-", elevationNames()))
	fmt.Fprintf(&b, "| `--elevation-<level>-seam` | %s | the hairline a raise draws at its own edge where the scheme has no step left to tell it by fill — `transparent` where the fill tells it. The backdrop has none: nothing stands on the backdrop |\n", joinTokens("--elevation-", elevationSeamNames()))
	fmt.Fprintf(&b, "| `--elevation-<level>-hairline` | %s | the hairline two regions that SHARE a level's fill are parted by — what a group draws at its own edge, and never `transparent`, because a group has no fill of its own and the line is the whole of what says where it ends. The backdrop has none: nothing is grouped on the bare window plane |\n", joinTokens("--elevation-", elevationHairlineNames()))
	fmt.Fprintf(&b, "| `--elevation-<level>-<state>` | %s | each level's own interaction walk — what a control with no fill of its own takes the surface under it to when hovered or pressed. Taken FROM the level's fill rather than named as a ramp step, because a level is not a ramp step in both schemes |\n", joinTokens("--elevation-", elevationStateNames()))
	fmt.Fprintf(&b, "| `--shadow-<level>` | %s | dp box-shadows — the OPT-IN cue for floating transients (menus, dialogs, tooltips) layered over the tonal fill; resting surfaces use the fill alone |\n", joinTokens("--shadow-", elevationNames()))
	fmt.Fprintf(&b, "| `--ease-<name>` | %s | MD3 easing presets as `cubic-bezier()`; emphasized is the documented single-bezier stand-in for MD3's two-segment path |\n", joinTokens("--ease-", easeNames()))
	fmt.Fprintf(&b, "| `--duration-<stop>` | %s | MD3-pinned duration stops, ms; the reduce-motion variant zeroes them |\n", joinTokens("--duration-", durationNames()))
	b.WriteString("| interaction states | `--focus-ring-width`, `--state-disabled-opacity` | the ring's 2 px stroke and the disabled fade fraction for `color-mix()` — both mode-invariant, unlike the ring's colour, which is measured against a surface that flips and so sits with the colours above |\n")
	b.WriteString("| scrim | `--color-scrim` | the modal backdrop dimmer: translucent black, identical in both modes — a scrim dims by reducing luminance, so it never flips with `.dark`. The alpha is the sRGB-compositing equivalent of the Gio pattern's 50% linear-space black |\n\n")

	b.WriteString("## Step purposes\n\n" +
		"| Step | Job |\n| --- | --- |\n" +
		"| 100 | tinted fill · the window's backdrop |\n" +
		"| 200 | tinted fill · one step off the backdrop |\n" +
		"| 300 | hover · subtle border, separator |\n" +
		"| 400 / 600 / 800 | intermediate steps; interaction states walk through them |\n" +
		"| 500 | mid-value reference · strong border |\n" +
		"| 700 | low-contrast text (Lc ≥ 60) · pressed |\n" +
		"| 900 | high-contrast body text (Lc ≥ 90) · pressed |\n\n" +
		"The pinned base — not a ramp step — is the solid fill; hover and pressed on a\n" +
		"solid walk one and two steps from the pin toward 900.\n\n")

	b.WriteString("## Component classes\n\n" +
		"`styles.css` ends with the component class layer, defined over the tokens\n" +
		"above — no literal colours anywhere, the only literal lengths being the\n" +
		"component constants the Gio side also hardcodes (the 16 dp\n" +
		"checkbox/radio glyph, its 8 dp dot, the 16 dp dropdown chevron, the\n" +
		"1/2 dp input borders) — so it flips to `.dark` and densifies to\n" +
		"`.compact` with the sheet. Every colour in it is the platform's own\n" +
		"name for what that element is on the platform, the same mapping the Gio\n" +
		"components take: no role, no ramp step, no level, no derivation. Every\n" +
		"pointer/keyboard state rule carries a forcing twin class (`.is-hover`,\n" +
		"`.is-active`, `.is-focus`, `.is-checked`) grouped into the same rule, so\n" +
		"a static page can show a state with exactly the live declarations;\n" +
		"disabled is forced with the native attribute.\n\n" +
		"A coverage composites the same on both sides, and that is what lets a\n" +
		"rule name a platform colour and stop: the platform's labels, seams,\n" +
		"overlays and focus ring are a colour at a coverage over whatever lies\n" +
		"beneath, a browser composites `#rrggbbaa` in encoded sRGB, and so does\n" +
		"`theme/color.Flatten` on the Gio side. Where the Gio component flattens\n" +
		"a name onto its own fill, the CSS lets the element's background paint\n" +
		"under the border, as it does by default; where it flattens onto the\n" +
		"surface the control stands on instead — a text field's focus ring, a\n" +
		"checkbox's edge — the rule sets `background-clip: padding-box` so the\n" +
		"edge composites over the page. That pair of clips is the whole of what\n" +
		"a control needs to know about its host; nothing is handed down.\n\n" +
		"`.btn` is the button, **filled** by default: `--platform-control-accent`\n" +
		"under `--platform-alternate-selected-control-text`, which is the\n" +
		"platform's default action. Two modifier classes select the less\n" +
		"pronounced variants — `.btn.tonal`, the platform's ordinary push button\n" +
		"(`--platform-push-button-fill` under `--platform-control-text`, inside a\n" +
		"`--platform-separator` hairline), and `.btn.ghost`, its borderless kind\n" +
		"(no fill, `--platform-control-text`). Nothing tints on hover: a Finder\n" +
		"toolbar button does and a Save dialog's push button does not, and this\n" +
		"sheet's classes are push buttons. Held (`:active`),\n" +
		"`--platform-press-overlay` goes over whatever fill the variant carries\n" +
		"and over the page where it carries none. Keyboard focus\n" +
		"(`:focus-visible`) keeps the resting fill and insets\n" +
		"`--platform-keyboard-focus-indicator` at `--focus-ring-width` — the same\n" +
		"ring at the same width in every variant, because keyboard visibility is\n" +
		"not a prominence property. Disabled (`:disabled`) is the platform's own\n" +
		"answer rather than a fade: the fill falls back to the push button's\n" +
		"inside the separator hairline and every foreground becomes\n" +
		"`--platform-disabled-control-text`. `.btn.icon` is the icon-only form: a\n" +
		"square the density's control height on a side, the glyph (an inline SVG\n" +
		"on `currentColor`) inset by the density's vertical padding.\n\n" +
		"`.badge` is the inline annotation: `label-medium` text on the platform's\n" +
		"system colour for the status it carries, under\n" +
		"`--platform-alternate-selected-control-text` — white in both\n" +
		"appearances, which is how the platform draws a count badge. The default\n" +
		"is `--platform-system-gray`, the platform naming no colour for \"no\n" +
		"status\"; `.badge.success` / `.badge.warning` / `.badge.error` /\n" +
		"`.badge.info` are systemGreen, systemOrange, systemRed and systemBlue.\n" +
		"Never invert the pair and never tint the system colour toward the\n" +
		"surface. No boundary and no vertical padding, so its height is the\n" +
		"role's line box; the side padding is `--space-2` and the corner is\n" +
		"`--radius-base`, deliberately not the pill a chip wears. A badge is\n" +
		"read, not used: no interaction states.\n\n" +
		"The form controls dress native elements — no script anywhere:\n" +
		"`.input` (text `<input>`, and `<select class=\"input select\">` inside a\n" +
		"`.select-wrap` for the chevron), `.checkbox` and `.radio` on their\n" +
		"native input types with `appearance: none`. They resolve exactly as\n" +
		"`components/input` does: `--platform-text-background` under\n" +
		"`--platform-text`, `--platform-placeholder-text` for a prompt,\n" +
		"`--platform-field-edge` on the resting edge, focus replacing that edge\n" +
		"with `--platform-keyboard-focus-indicator` at `--focus-ring-width`, and\n" +
		"`--platform-disabled-control-text` where the control cannot be used —\n" +
		"the fill staying exactly where it was, because the platform fades the\n" +
		"wording and leaves the control. A text field's height floor is\n" +
		"`--density-field-height`, not the control height: the platform draws a\n" +
		"field shorter than the button beside it. The dropdown trigger is the\n" +
		"exception in this family and is a BUTTON rather than a field, so\n" +
		"`.select` takes the push button's fill, the separator hairline and the\n" +
		"control height. Checked, the box is `--platform-control-accent` under a\n" +
		"check mark drawn from the icon set's grid as two gradient bands — a fill\n" +
		"says a colour was applied and only the mark says what it means. The\n" +
		"radio's selected state is the same accent filling the circle with an\n" +
		"8 dp white dot at its centre.\n\n" +
		"`.card` is the platform's grouped box: `--platform-card-fill`, a small\n" +
		"step of fill from the surface it stands on, with no hairline and no\n" +
		"shadow. `.group` is the other half of that ruling — a\n" +
		"`--platform-separator` hairline around related components, taking the\n" +
		"fill of the surface it is in and declaring none. `.table` prints on\n" +
		"`--platform-control-background` with rows a `--density-row-height`\n" +
		"tall, `--platform-grid` closing each and `--platform-separator` closing\n" +
		"the header band. The navigation family — `.navbar`, `.tabs`, `.sidebar`\n" +
		"and `.crumbs` — stands on `--platform-sidebar-material`, the chrome, and\n" +
		"draws the separator where two flush regions meet; selection is\n" +
		"`--platform-selected-content-background`, as an underline on a link or a\n" +
		"tab and as the row's own fill on a rail. The overlay family —\n" +
		"`.scrim`/`.dialog`, `.popover`, `.tooltip`, `.toast` — is filled with\n" +
		"`--platform-window-background`, which is what every floating surface on\n" +
		"this platform is filled with, and floats on\n" +
		"`--platform-floating-shadow`.\n\n")

	b.WriteString("## Elevation: default vs opt-in\n\n" +
		"Elevation is tonal, and it climbs toward the light: **in both schemes,\n" +
		"every level is lighter than the one beneath it.** One perceptual rule,\n" +
		"no second rule for the dark scheme and no mirror — a surface nearer the\n" +
		"viewer catches more light, and reflectance does not invert when the room\n" +
		"goes dark. Six levels, counted from the backdrop up toward the reader:\n\n" +
		"| Level | What wears it |\n| --- | --- |\n" +
		"| `--elevation-backdrop` | nothing: the bare window plane, showing wherever nothing stands; the window's darkest region |\n" +
		"| `--elevation-chrome` | the chrome regions — navbar, toolbar, sidebar, inspector, status bar, pane |\n" +
		"| `--elevation-0` | the content surface, the bg pin |\n" +
		"| `--elevation-1` | raised on the content — cards, code fences, text fields; the raise walked from `--elevation-0`, not a table entry |\n" +
		"| `--elevation-2` | floating — dialogs, toasts |\n" +
		"| `--elevation-3` | floating, nearest the scheme's light extreme — menus, popovers, tooltips |\n\n" +
		"Read that down and the fill gets lighter, in `:root` and in `.dark`\n" +
		"alike. Chrome is window-scale only: the trim inside a component or a\n" +
		"pattern — a card's header, a dialog's footer — is that thing's\n" +
		"structure and takes no level of its own. The chrome level is the one\n" +
		"the ramp does not place: its step under the content is measured off the\n" +
		"platform rather than derived, and the two schemes measure\n" +
		"differently — about 4.9 L\\* under light content, about 1.5 under dark,\n" +
		"where a full ramp step would read as a hole rather than as chrome.\n" +
		"That asymmetry is the platform's own, not a rule mirrored between the\n" +
		"schemes. The backdrop takes that step scaled by the ramp's own\n" +
		"proportion, because no platform capture shows a window plane beneath\n" +
		"its chrome to measure. A chrome region that floats is still chrome\n" +
		"and still fills at the chrome level: what says it is a floating object\n" +
		"is its own hairline edge and its shadow, never a lighter fill.\n" +
		"The levels stop at 3: desktop has no six-deep stack. Note the\n" +
		"sizes — a light scheme has spent almost all of the tonal axis on its\n" +
		"content, so its levels above the content are separated by a fraction of\n" +
		"an L\\* and the derived line (`--elevation-<level>-hairline`,\n" +
		"`--dialog-border`, `--popover-border`) is what says where a surface is.\n" +
		"That is what the desktop applications this system is judged against\n" +
		"measure too.\n\n" +
		"The surface fill is the **default** cue. The dp shadow is the **opt-in**\n" +
		"secondary cue, reserved for floating transients — menus, dialogs,\n" +
		"tooltips — which layer `--shadow-N` over their tonal fill. Resting\n" +
		"surfaces never cast one.\n\n")

	b.WriteString("## Density\n\n" +
		"Two published settings, one variable family: comfortable (24 dp controls,\n" +
		"20 dp chips, 8/2 dp padding) is the `:root` default; compact (19 dp\n" +
		"controls, 15 dp chips, 7/0 dp padding) is the `.compact` class override,\n" +
		"scoping to any subtree the way `.dark` scopes colours. The chip height is\n" +
		"the control height less 4 dp in both settings — one relation, not a second\n" +
		"scale. A text field and a stacked row are not controls and carry their own\n" +
		"measured heights: `--density-field-height` (27 dp comfortable, 21 compact)\n" +
		"and `--density-row-height` (20 dp, 19 compact).\n" +
		"`--density-min-hit-target` (44 dp, WCAG 2.5.5) is deliberately not\n" +
		"overridden: compact shrinks the drawn control, never the clickable area.\n" +
		"`theme.json` records both settings' metrics plus which one the theme runs.\n\n")

	b.WriteString("## Motion\n\n" +
		"The MD3 easing presets are emitted as `cubic-bezier()` variables and the\n" +
		"five duration stops in ms, each pinned to one MD3 duration role. The spring\n" +
		"presets (default/snappy/gentle) are Go-side damped-oscillator physics with\n" +
		"no CSS counterpart, so they live only in `theme.json`'s motion parameters.\n" +
		"Under the OS reduce-motion preference the theme emits the same scale with\n" +
		"every duration zeroed; the sheet is generated from the non-reduced scale.\n\n")

	b.WriteString("## Reproducibility\n\n" +
		"`theme.json` records the seed (hex plus its OKLCh hue and sat), the pinned role\n" +
		"hexes per mode, the faces, the base radius, the measured lightness scales, both\n" +
		"density settings' metrics, the elevation model (surface steps and shadow dps\n" +
		"per level) and the motion set (durations, easings, springs).\n" +
		"`FromSeed(seed)` regenerates every ramp and pin from the seed alone — a\n" +
		"round-trip test in `theme/export` asserts it — so the file, not this text,\n" +
		"is the contract. To rebrand, rerun `vg-tokens -seed #rrggbb`; every page here\n" +
		"reflows because nothing in them is hard-coded.\n\n" +
		"Fonts: the tokens name " + s.Typography.BodyLarge.Typeface + " (and " + s.Typography.Code.Typeface + " for code); the pages fall\n" +
		"back to system faces when they are not installed. An increased-contrast palette variant exists Go-side\n" +
		"(`tokens.FromSeedHighContrast`, driven by the OS contrast preference); it is\n" +
		"not part of this export.\n")

	return b.String()
}

// spaceNames, radiusNames and elevationNames list each scale's key names in
// sheet order, for the readme's enumerations.
func spaceNames() []string {
	names := make([]string, len(spaceKeys))
	for i, k := range spaceKeys {
		names[i] = k.name
	}
	return names
}

func radiusNames() []string {
	names := make([]string, len(radiusKeys))
	for i, k := range radiusKeys {
		names[i] = k.name
	}
	return names
}

func elevationNames() []string {
	names := make([]string, len(elevationLevels))
	for i, k := range elevationLevels {
		names[i] = k.name
	}
	return names
}

// elevationStateNames lists each level's interaction walk in sheet order —
// backdrop-hover, backdrop-active, 0-hover, and so on. The walk is a family
// of its own because a level is not a ramp step in both schemes, so a state
// taken from a level cannot be spelled as that step's neighbour.
// elevationSeamNames lists the seam each standable level owes what stands on
// it, in sheet order. The backdrop is absent: nothing stands on it.
func elevationSeamNames() []string {
	names := make([]string, 0, len(standableLevels))
	for _, k := range standableLevels {
		names = append(names, k.name+"-seam")
	}
	return names
}

// elevationHairlineNames lists the hairline each standable level's own fill
// is parted from itself by, in sheet order. The backdrop is absent: nothing
// is grouped on it.
func elevationHairlineNames() []string {
	names := make([]string, 0, len(standableLevels))
	for _, k := range standableLevels {
		names = append(names, k.name+"-hairline")
	}
	return names
}

func elevationStateNames() []string {
	names := make([]string, 0, 2*len(elevationLevels))
	for _, k := range elevationLevels {
		names = append(names, k.name+"-hover", k.name+"-active")
	}
	return names
}

// densityNames, easeNames and durationNames list the density metric, easing
// preset and duration stop names in sheet order, for the readme's
// enumerations.
func densityNames() []string {
	names := make([]string, len(densityMetrics))
	for i, m := range densityMetrics {
		names[i] = m.name
	}
	return names
}

func easeNames() []string {
	names := make([]string, len(easeRoles))
	for i, r := range easeRoles {
		names[i] = r.name
	}
	return names
}

func durationNames() []string {
	names := make([]string, len(durationStops))
	for i, s := range durationStops {
		names[i] = s.name
	}
	return names
}

// joinTokens renders a comma-separated code list of prefix+name tokens.
func joinTokens(prefix string, names []string) string {
	out := make([]string, len(names))
	for i, n := range names {
		out[i] = "`" + prefix + n + "`"
	}
	return strings.Join(out, ", ")
}
